spring.application.name=rest-api-demo
spring.datasource.url=jdbc:mysql://localhost:3306/comercio
spring.datasource.username=root
spring.datasource.password=Temp2024

# Para la configuracion del ORM Hibernate 
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

demo.app.jwtSecret=94bcf3540d0d72fc773ea75eb9f2e8eb9b5aafc67d456146e9f1632e215c7bf7e6bbd9de0ccfe54cb9ac48d0ea178b570c28b714c11ec3bad5c08582be5b251d
demo.app.jwtExpirationMs=86400000